name = "PkgExt"
uuid = "6ec7f1b7-1128-4ac4-a8d2-66b9668d42e7"
authors = ["Paco Ho"]
version = "1.0.0-DEV"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
